/*
 * Copyright (c) 2026 Bang & Olufsen A/S, Denmark
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_UART_MSPM0_UART_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_UART_MSPM0_UART_H_

#define MSPM0_UART_RX_FIFO_LEVEL_ONE_ENTRY 0
#define MSPM0_UART_RX_FIFO_LEVEL_1_4_FULL  1
#define MSPM0_UART_RX_FIFO_LEVEL_1_2_FULL  2
#define MSPM0_UART_RX_FIFO_LEVEL_3_4_FULL  3
#define MSPM0_UART_RX_FIFO_LEVEL_FULL      4

#define MSPM0_UART_TX_FIFO_LEVEL_1_4_EMPTY 0
#define MSPM0_UART_TX_FIFO_LEVEL_1_2_EMPTY 1
#define MSPM0_UART_TX_FIFO_LEVEL_3_4_EMPTY 2
#define MSPM0_UART_TX_FIFO_LEVEL_ONE_ENTRY 3
#define MSPM0_UART_TX_FIFO_LEVEL_EMPTY     4

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_UART_MSPM0_UART_H_ */
